spring.liquibase.change-log: liquibase/changelog_root.yml
spring.jpa.hibernate.ddl-auto: validate
spring.datasource.url: jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.jpa.properties.hibernate.format_sql: true

by.sakuuj.elasticsearch.server.url: http://localhost:9200
by.sakuuj.elasticsearch.password: elastic
by.sakuuj.elasticsearch.main-index.name: products_and_skus
by.sakuuj.elasticsearch.json-files.index.base-path: products_and_skus